package com.pixeltranslator.multi.ui

/**
 * On-screen UI chrome, translated per-language. Keyed by the user's Language A
 * selection so the app speaks to its operator in their language. The
 * About and Disclaimer screen bodies have their own in-screen language
 * pickers and are not governed by this table.
 */
data class UiStrings(
    val title: String,
    val aboutButton: String,
    val disclaimerButton: String,
    val clearButton: String,
    val modelQuick: String,
    val modelHighQuality: String,
    val statusReady: String,
    val statusLoading: String,
    val statusListening: String,
    val statusTranslating: String,
    val statusSpeaking: String,
    val statusNoVoice: String,
    val micPermissionRequired: String,
    val loadingModels: String,
    val holdToSpeak: String,
    /** Takes both languages' native names and returns the empty-state sentence. */
    val emptyPlaceholder: (nativeA: String, nativeB: String) -> String,
    // Disclaimer + About screen chrome.
    val disclaimerScreenTitle: String,
    val playAloudLabel: String,
    val beginButton: String,
    val aboutScreenTitle: String,
    val aboutScreenSubtitle: String,
    val closeButton: String
)

object Strings {
    fun forLanguage(lang: Language): UiStrings = when (lang) {
        Language.ENGLISH -> UiStrings(
            title = "AI Translator",
            aboutButton = "About",
            disclaimerButton = "Disclaimer",
            clearButton = "Clear",
            modelQuick = "Faster",
            modelHighQuality = "Higher Accuracy",
            statusReady = "Ready",
            statusLoading = "Loading…",
            statusListening = "Listening…",
            statusTranslating = "Translating…",
            statusSpeaking = "Speaking…",
            statusNoVoice = "Ready (no voice installed)",
            micPermissionRequired = "Microphone permission required",
            loadingModels = "Loading models…",
            holdToSpeak = "Hold to speak",
            emptyPlaceholder = { a, b -> "Speak in $a or $b.\nThe app will translate into the other." },
            disclaimerScreenTitle = "Before you begin",
            playAloudLabel = "Play aloud:",
            beginButton = "Begin",
            aboutScreenTitle = "About",
            aboutScreenSubtitle = "Fully offline, fully private",
            closeButton = "Close"
        )
        Language.SPANISH -> UiStrings(
            title = "Traductor con IA",
            aboutButton = "Acerca",
            disclaimerButton = "Aviso",
            clearButton = "Borrar",
            modelQuick = "Más rápido",
            modelHighQuality = "Mayor precisión",
            statusReady = "Listo",
            statusLoading = "Cargando…",
            statusListening = "Escuchando…",
            statusTranslating = "Traduciendo…",
            statusSpeaking = "Hablando…",
            statusNoVoice = "Listo (sin voz instalada)",
            micPermissionRequired = "Se necesita permiso del micrófono",
            loadingModels = "Cargando modelos…",
            holdToSpeak = "Mantén presionado para hablar",
            emptyPlaceholder = { a, b -> "Habla en $a o $b.\nLa app traducirá al otro idioma." },
            disclaimerScreenTitle = "Antes de empezar",
            playAloudLabel = "Reproducir en voz alta:",
            beginButton = "Comenzar",
            aboutScreenTitle = "Acerca",
            aboutScreenSubtitle = "Completamente sin conexión, completamente privado",
            closeButton = "Cerrar"
        )
        Language.FRENCH -> UiStrings(
            title = "Traducteur IA",
            aboutButton = "À propos",
            disclaimerButton = "Avis",
            clearButton = "Effacer",
            modelQuick = "Plus rapide",
            modelHighQuality = "Plus précis",
            statusReady = "Prêt",
            statusLoading = "Chargement…",
            statusListening = "Écoute…",
            statusTranslating = "Traduction…",
            statusSpeaking = "Lecture…",
            statusNoVoice = "Prêt (aucune voix installée)",
            micPermissionRequired = "Autorisation du microphone requise",
            loadingModels = "Chargement des modèles…",
            holdToSpeak = "Maintenir pour parler",
            emptyPlaceholder = { a, b -> "Parlez en $a ou en $b.\nL'app traduira vers l'autre langue." },
            disclaimerScreenTitle = "Avant de commencer",
            playAloudLabel = "Lire à voix haute :",
            beginButton = "Commencer",
            aboutScreenTitle = "À propos",
            aboutScreenSubtitle = "Entièrement hors ligne, entièrement privé",
            closeButton = "Fermer"
        )
        Language.GERMAN -> UiStrings(
            title = "KI-Übersetzer",
            aboutButton = "Info",
            disclaimerButton = "Hinweis",
            clearButton = "Löschen",
            modelQuick = "Schneller",
            modelHighQuality = "Genauer",
            statusReady = "Bereit",
            statusLoading = "Lade…",
            statusListening = "Höre zu…",
            statusTranslating = "Übersetze…",
            statusSpeaking = "Spreche…",
            statusNoVoice = "Bereit (keine Stimme installiert)",
            micPermissionRequired = "Mikrofon-Berechtigung erforderlich",
            loadingModels = "Modelle werden geladen…",
            holdToSpeak = "Zum Sprechen gedrückt halten",
            emptyPlaceholder = { a, b -> "Sprechen Sie $a oder $b.\nDie App übersetzt in die andere Sprache." },
            disclaimerScreenTitle = "Bevor Sie beginnen",
            playAloudLabel = "Vorlesen:",
            beginButton = "Beginnen",
            aboutScreenTitle = "Info",
            aboutScreenSubtitle = "Vollständig offline, vollständig privat",
            closeButton = "Schließen"
        )
        Language.PORTUGUESE -> UiStrings(
            title = "Tradutor com IA",
            aboutButton = "Sobre",
            disclaimerButton = "Aviso",
            clearButton = "Limpar",
            modelQuick = "Mais rápido",
            modelHighQuality = "Maior precisão",
            statusReady = "Pronto",
            statusLoading = "Carregando…",
            statusListening = "Ouvindo…",
            statusTranslating = "Traduzindo…",
            statusSpeaking = "Falando…",
            statusNoVoice = "Pronto (sem voz instalada)",
            micPermissionRequired = "Permissão do microfone necessária",
            loadingModels = "Carregando modelos…",
            holdToSpeak = "Mantenha pressionado para falar",
            emptyPlaceholder = { a, b -> "Fale em $a ou $b.\nO app traduzirá para o outro idioma." },
            disclaimerScreenTitle = "Antes de começar",
            playAloudLabel = "Ler em voz alta:",
            beginButton = "Começar",
            aboutScreenTitle = "Sobre",
            aboutScreenSubtitle = "Totalmente offline, totalmente privado",
            closeButton = "Fechar"
        )
        Language.ITALIAN -> UiStrings(
            title = "Traduttore IA",
            aboutButton = "Info",
            disclaimerButton = "Avviso",
            clearButton = "Cancella",
            modelQuick = "Più veloce",
            modelHighQuality = "Più preciso",
            statusReady = "Pronto",
            statusLoading = "Caricamento…",
            statusListening = "In ascolto…",
            statusTranslating = "Traduzione…",
            statusSpeaking = "In riproduzione…",
            statusNoVoice = "Pronto (nessuna voce installata)",
            micPermissionRequired = "Permesso microfono richiesto",
            loadingModels = "Caricamento modelli…",
            holdToSpeak = "Tieni premuto per parlare",
            emptyPlaceholder = { a, b -> "Parla in $a o $b.\nL'app tradurrà nell'altra lingua." },
            disclaimerScreenTitle = "Prima di iniziare",
            playAloudLabel = "Leggi ad alta voce:",
            beginButton = "Inizia",
            aboutScreenTitle = "Info",
            aboutScreenSubtitle = "Completamente offline, completamente privato",
            closeButton = "Chiudi"
        )
        Language.CHINESE -> UiStrings(
            title = "AI 翻译器",
            aboutButton = "关于",
            disclaimerButton = "声明",
            clearButton = "清除",
            modelQuick = "更快",
            modelHighQuality = "更准确",
            statusReady = "就绪",
            statusLoading = "加载中…",
            statusListening = "聆听中…",
            statusTranslating = "翻译中…",
            statusSpeaking = "朗读中…",
            statusNoVoice = "就绪（未安装语音）",
            micPermissionRequired = "需要麦克风权限",
            loadingModels = "正在加载模型…",
            holdToSpeak = "按住说话",
            emptyPlaceholder = { a, b -> "请说 $a 或 $b。\n应用将翻译为另一种语言。" },
            disclaimerScreenTitle = "开始之前",
            playAloudLabel = "朗读：",
            beginButton = "开始",
            aboutScreenTitle = "关于",
            aboutScreenSubtitle = "完全离线，完全私密",
            closeButton = "关闭"
        )
        Language.JAPANESE -> UiStrings(
            title = "AI翻訳",
            aboutButton = "アプリ情報",
            disclaimerButton = "注意事項",
            clearButton = "クリア",
            modelQuick = "高速",
            modelHighQuality = "高精度",
            statusReady = "準備完了",
            statusLoading = "読み込み中…",
            statusListening = "聞き取り中…",
            statusTranslating = "翻訳中…",
            statusSpeaking = "読み上げ中…",
            statusNoVoice = "準備完了（音声未インストール）",
            micPermissionRequired = "マイクの権限が必要です",
            loadingModels = "モデルを読み込み中…",
            holdToSpeak = "押しながら話す",
            emptyPlaceholder = { a, b -> "$a または $b で話してください。\nアプリがもう一方の言語に翻訳します。" },
            disclaimerScreenTitle = "はじめる前に",
            playAloudLabel = "読み上げ:",
            beginButton = "はじめる",
            aboutScreenTitle = "アプリ情報",
            aboutScreenSubtitle = "完全オフライン、完全プライベート",
            closeButton = "閉じる"
        )
        Language.KOREAN -> UiStrings(
            title = "AI 번역기",
            aboutButton = "정보",
            disclaimerButton = "주의사항",
            clearButton = "지우기",
            modelQuick = "더 빠름",
            modelHighQuality = "더 정확",
            statusReady = "준비됨",
            statusLoading = "로딩 중…",
            statusListening = "듣는 중…",
            statusTranslating = "번역 중…",
            statusSpeaking = "말하는 중…",
            statusNoVoice = "준비됨 (음성 미설치)",
            micPermissionRequired = "마이크 권한이 필요합니다",
            loadingModels = "모델 로딩 중…",
            holdToSpeak = "누르고 말하기",
            emptyPlaceholder = { a, b -> "$a 또는 ${b}로 말씀해 주세요.\n앱이 다른 언어로 번역합니다." },
            disclaimerScreenTitle = "시작하기 전에",
            playAloudLabel = "소리 내어 읽기:",
            beginButton = "시작",
            aboutScreenTitle = "정보",
            aboutScreenSubtitle = "완전 오프라인, 완전 비공개",
            closeButton = "닫기"
        )
        Language.HINDI -> UiStrings(
            title = "एआई अनुवादक",
            aboutButton = "परिचय",
            disclaimerButton = "सूचना",
            clearButton = "साफ़",
            modelQuick = "तेज़",
            modelHighQuality = "अधिक सटीक",
            statusReady = "तैयार",
            statusLoading = "लोड हो रहा है…",
            statusListening = "सुन रहा है…",
            statusTranslating = "अनुवाद हो रहा है…",
            statusSpeaking = "बोल रहा है…",
            statusNoVoice = "तैयार (कोई आवाज़ इंस्टॉल नहीं)",
            micPermissionRequired = "माइक्रोफ़ोन की अनुमति आवश्यक है",
            loadingModels = "मॉडल लोड हो रहे हैं…",
            holdToSpeak = "बोलने के लिए दबाए रखें",
            emptyPlaceholder = { a, b -> "$a या $b में बोलें।\nऐप दूसरी भाषा में अनुवाद करेगा।" },
            disclaimerScreenTitle = "शुरू करने से पहले",
            playAloudLabel = "ज़ोर से पढ़ें:",
            beginButton = "शुरू करें",
            aboutScreenTitle = "परिचय",
            aboutScreenSubtitle = "पूरी तरह ऑफ़लाइन, पूरी तरह निजी",
            closeButton = "बंद करें"
        )
        Language.ARABIC -> UiStrings(
            title = "مترجم بالذكاء الاصطناعي",
            aboutButton = "حول",
            disclaimerButton = "إشعار",
            clearButton = "مسح",
            modelQuick = "أسرع",
            modelHighQuality = "أعلى دقة",
            statusReady = "جاهز",
            statusLoading = "جارٍ التحميل…",
            statusListening = "يستمع…",
            statusTranslating = "جارٍ الترجمة…",
            statusSpeaking = "يتحدث…",
            statusNoVoice = "جاهز (لا يوجد صوت مثبت)",
            micPermissionRequired = "يتطلب إذن الميكروفون",
            loadingModels = "جارٍ تحميل النماذج…",
            holdToSpeak = "اضغط مطولاً للتحدث",
            emptyPlaceholder = { a, b -> "تحدث بـ$a أو $b.\nسيقوم التطبيق بالترجمة إلى اللغة الأخرى." },
            disclaimerScreenTitle = "قبل البدء",
            playAloudLabel = "قراءة بصوت عالٍ:",
            beginButton = "ابدأ",
            aboutScreenTitle = "حول",
            aboutScreenSubtitle = "دون اتصال بالكامل، خاص بالكامل",
            closeButton = "إغلاق"
        )
        Language.RUSSIAN -> UiStrings(
            title = "ИИ-переводчик",
            aboutButton = "О приложении",
            disclaimerButton = "Примечание",
            clearButton = "Очистить",
            modelQuick = "Быстрее",
            modelHighQuality = "Точнее",
            statusReady = "Готово",
            statusLoading = "Загрузка…",
            statusListening = "Слушаю…",
            statusTranslating = "Перевод…",
            statusSpeaking = "Говорю…",
            statusNoVoice = "Готово (голос не установлен)",
            micPermissionRequired = "Требуется разрешение на микрофон",
            loadingModels = "Загрузка моделей…",
            holdToSpeak = "Удерживайте, чтобы говорить",
            emptyPlaceholder = { a, b -> "Говорите на $a или $b.\nПриложение переведёт на другой язык." },
            disclaimerScreenTitle = "Перед началом",
            playAloudLabel = "Прочитать вслух:",
            beginButton = "Начать",
            aboutScreenTitle = "О приложении",
            aboutScreenSubtitle = "Полностью офлайн, полностью приватно",
            closeButton = "Закрыть"
        )
        Language.VIETNAMESE -> UiStrings(
            title = "Dịch AI",
            aboutButton = "Giới thiệu",
            disclaimerButton = "Lưu ý",
            clearButton = "Xóa",
            modelQuick = "Nhanh hơn",
            modelHighQuality = "Chính xác hơn",
            statusReady = "Sẵn sàng",
            statusLoading = "Đang tải…",
            statusListening = "Đang nghe…",
            statusTranslating = "Đang dịch…",
            statusSpeaking = "Đang đọc…",
            statusNoVoice = "Sẵn sàng (chưa cài giọng nói)",
            micPermissionRequired = "Yêu cầu quyền truy cập micrô",
            loadingModels = "Đang tải mô hình…",
            holdToSpeak = "Giữ để nói",
            emptyPlaceholder = { a, b -> "Hãy nói bằng $a hoặc $b.\nỨng dụng sẽ dịch sang ngôn ngữ còn lại." },
            disclaimerScreenTitle = "Trước khi bắt đầu",
            playAloudLabel = "Đọc thành tiếng:",
            beginButton = "Bắt đầu",
            aboutScreenTitle = "Giới thiệu",
            aboutScreenSubtitle = "Hoàn toàn ngoại tuyến, hoàn toàn riêng tư",
            closeButton = "Đóng"
        )
    }
}
